spring.application.name: YourSSU_Onboarding
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/onboarding_task
    username: SSUOnboard
    password: awesomeyourssu12!@
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8001